### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by haridave0718** [INFO-523-Exercises/project-final-The-Algo-Rhythms#1]
The following is the peer review of the project proposal by Team MineCrafters. The team members that participated in this review are 

- Hari Dave - @haridave0718
- Sarthak Miglani - @sarthakMiglani726
- Partha Koundinya P - @partha-pkp
- Vinu Kevin Diesel - @Kevin-diesel-1194
- Syed Aslam Sheik Dawood - @Syedaslamsheikdawood
<br>

- Describe the goal of the project.
    - Using Twitter, the project wants to study what people say during disasters to find patterns, check if the information is true, and better understand what's happening. The main goal is to keep people safe by knowing what's going on and understanding how people feel.

- Describe the data used or collected.
    - The CREDBANK corpus data was put together from October 2014 to February 2015, capturing tweets on different topics. These tweets are sorted into four files, each with info on events, credibility ratings, and whether they're classified as events or non-events.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
    - In the first week, they will explore and preprocess the dataset, converting it into binary classes and extracting key features. Then, they'll train and validate a classification model.

    - Week 2 involves extracting entities from tweets using Named Entity Recognition (NER) techniques and linking them to tweets.

    - Week 3 focuses on setting up a real-time streaming client, defining filters for disaster-related tweets, and processing and storing incoming data.

    - In Week 4, they will be visualizing the data in a GUI, including geographic locations and an analysis dashboard.

    - In Week 5 they will be dealing with enhancing the GUI with mapping features, intelligent analytics on disasters, and an interface for analysis.

    - Finally, in Week 6,  deployment of the GUI, testing on real-time data, incorporating feedback, and presenting the final project showcase.

- Is there anything that is unclear from the proposal?
    - The timeframe and age of the data have caught our attention, and we are wondering about the approach the model will take for real-time classification given the relatively older dataset.

- Provide constructive feedback on how the team might be able to improve their project.
    - The overall planning on how to go about the project is clear. By considering a relatively recent dataset, the model might give much more accurate results.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
    - We are looking forward to seeing how the GUI will be built.

- Provide constructive feedback on any issues with file and/or code organization.
    - It would have been nice if the dataset were loaded to the proposal page with some inline code as mentioned in the instructions provided.
    - Also according to the guidelines you were also asked to mention the organization of the repository.

- (Optional) Any further comments or feedback?
    - Best wishes from Team MineCrafters.

**Comment by visalakshi2001** [comment]
Thank you Team MineCrafters for the review.
We found your points greatly helpful, and we have made changes accordingly.

We will now close this issue as done.
