### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Aravind-shrenivas** [INFO-523-Exercises/project-final-The-Algo-Rhythms#2]
The following is the peer review of the project proposal by **Feature Finders Club** . The team members that participated in this review are 

- Eshaan Mathakari - @eshaanmathakari
- Sanjay Bhargav Siddi - @sanjaybhargavsiddi
- Likith Kumar Dundigalla - @LikithKumarDundigalla
- Aravind shrenivas Murali - @Aravind-shrenivas
- Vamsi Vadala - @Vamsi-Vadala

- Describe the goal of the project.
The goal of their project is to use Twitter as a valuable tool for gaining real-time information and insights during disasters by analysing Twitter conversations and trends, finding patterns, verifying the accuracy of information, enhancing situational awareness, which ultimately can help save lives.

- Describe the data used or collected.
The dataset consists of two primary components: CREDBANK and the academictwitteR package. CREDBANK includes streaming tweets, topics, and credibility ratings for events. It comprises two key files, one with credibility ratings and explanations by turkers for each topic, and another with tweets related to these topics. This dataset is essential for training models to assess tweet credibility. On the other hand, the academictwitteR package is designed for efficiently collecting and storing tweets from the v2 API endpoint.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Because disasters are dynamic events, proactive information gathering and analysis is necessary. Traditional techniques are not flexible enough to change quickly, which makes it difficult for emergency responders to anticipate needs and deploy resources. To avoid false information and the accompanying fear, it is essential to make sure that information provided on Twitter during such situations is accurate and reliable.

- Is there anything that is unclear from the proposal?
1) You mentioned about GUI, would be clear if you mention more about it.
2)Would be clear if you write the plan in order of execution- Converting to Binary classes would make sense after the data processing rather than in exploration.
3)"Deploy the GUI and test on real-time data.
Make changes according to feedback."- would be better if you gave a clear picture about this.

- Provide constructive feedback on how the team might be able to improve their project.
1. Specify the metrics that will be employed to evaluate the model's performance. This could include accuracy in classifying real and fake tweets, etc. This makes sure everyone understands how well the model is working.
2. Explore opportunities to integrate your model with established disaster management systems. By this, your model can add extra strength to the whole disaster response setup, making it even better at handling emergencies.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are more interested on the GUI.

- Provide constructive feedback on any issues with file and/or code organization.
No issues.

- (Optional) Any further comments or feedback?
All the best!

**Comment by visalakshi2001** [comment]
Thank you Team Feature Finders Club for the review.
We found your points greatly helpful, and we have made changes accordingly.

We will now close this issue as done.
