### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/project-final-The-Algo-Rhythms#3]
Dear The Algo Rhythms: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |     2   |
| Proposal | 5         |      4.5  |
| Workflow | 1         |    1    |
| Teamwork | 1         |     1   |
| Total    | 10        |      8.5  |

Data: I commend you trying to get real-time data, but this is no longer possible. From the package's GitHub: Note this repo is now ARCHVIED due to changes to the Twitter API. The paid API means open-source development of this package is no longer feasible. I unfortunately cannot afford the API access fee for this project. 
Also note that I would like to see column data types as well. 
Proposal: the plan of attack should be fleshed out by now.

**Comment by visalakshi2001** [comment]
Hi Dr. Chism,

Thank you for the helpful feedback! We have adjusted the proposal with the feedback you suggested. Kindly take this forward for a regrade.

> Hope you have a wonderful Thanksgiving break!

Best,
The Algo-Rhythms

**Comment by Gchism94** [comment]
Your second score is **10/10**, so your final score is **9.25/10**
