### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Aravind-shrenivas** [INFO-523-Exercises/project-final-The-Algo-Rhythms#6]
The following is the peer review of the Presentation proposal by Feature Finders Club. The team members that participated in this review are 

- Eshaan Mathakari - @eshaanmathakari
- Sanjay Bhargav Siddi - @sanjaybhargavsiddi
- Likith Kumar Dundigalla - @LikithKumarDundigalla
- Aravind shrenivas Murali - @Aravind-shrenivas
- Vamsi Vadala - @Vamsi-Vadala

- Content: Is the research question well designed and is the data being used relevant to the research question?
yes

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
One doubt we have is that the team mentioned the density plot is a Uniform distribution, but the disaster plot is a bimodal distribution.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
most of the slides are full of text.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
yes, it was professional, it appears to be practiced. no one was reading off a script. and everyone got a chance to contribute to the presentation

**Comment by poojithapasala** [comment]
Suggested changes were made.
