### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Kevin-diesel-1194** [INFO-523-Exercises/project-final-The-Algo-Rhythms#7]
The following is the peer review of the Presentation proposal by Minecrafters. The team members that participated in this review are 

- Hari Dave - @haridave0718
- Sarthak Miglani - @sarthakMiglani726
- Partha Koundinya P - @partha-pkp
- Vinu Kevin Diesel - @Kevin-diesel-1194
- Syed Aslam Sheik Dawood - @Syedaslamsheikdawood

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, the visualizations were adequate, and the interpretations were accurate.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
All the texts were visible but the only issue was with the size of the plots. The size of the plots could have been a little bigger given that they had space.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
The presentation was great overall (especially the GUI section), everyone had something meaningful to talk about and it did look like a well-practiced presentation.

**Comment by poojithapasala** [comment]
Suggested changes were made to the presentation.
